// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ0ZohLWCt1NEnLzpx9vy0RUdoit8R53w',
    appId: '1:563531037147:web:3597fb9e097ae270e64ffe',
    messagingSenderId: '563531037147',
    projectId: 'foodpanda-clone-bacba',
    authDomain: 'foodpanda-clone-bacba.firebaseapp.com',
    storageBucket: 'foodpanda-clone-bacba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0aI23Z7e7Nuby_Z5XdEvVTYl9C_JL8RU',
    appId: '1:563531037147:android:67e90cbe62a3da6de64ffe',
    messagingSenderId: '563531037147',
    projectId: 'foodpanda-clone-bacba',
    storageBucket: 'foodpanda-clone-bacba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCabtISHKuWtIP13Y5jKWotGWvkbvE1S5o',
    appId: '1:563531037147:ios:0446b8b39dd031bfe64ffe',
    messagingSenderId: '563531037147',
    projectId: 'foodpanda-clone-bacba',
    storageBucket: 'foodpanda-clone-bacba.appspot.com',
    iosBundleId: 'com.example.cplForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCabtISHKuWtIP13Y5jKWotGWvkbvE1S5o',
    appId: '1:563531037147:ios:0446b8b39dd031bfe64ffe',
    messagingSenderId: '563531037147',
    projectId: 'foodpanda-clone-bacba',
    storageBucket: 'foodpanda-clone-bacba.appspot.com',
    iosBundleId: 'com.example.cplForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYaf2KA_4FxkVSba4pOij8BcL5e-sGuLE',
    appId: '1:563531037147:web:2e9dd60bf814ea70e64ffe',
    messagingSenderId: '563531037147',
    projectId: 'foodpanda-clone-bacba',
    authDomain: 'foodpanda-clone-bacba.firebaseapp.com',
    storageBucket: 'foodpanda-clone-bacba.appspot.com',
  );

}